export enum TipoEnfermedad {
    RESPIRATORIA = "RESPIRATORIA",
    DIGESTIVA = "DIGESTIVA",
    SISTEMANERVIOSO = "SISTEMANERVIOSO",
    PARASITARIA = "PARASITARIA",
    INTOXICACION = "INTOXICACION",
    TRAUMATOLOGICA = "TRAUMATOLOGICA"
}

