export enum TipoEnfermedad {
    RESPIRATORIA = "RESPIRATORIA",
    DIGESTIVA = "DIGESTIVA",
    SISTEMA_NERVIOSO = "SISTEMA_NERVIOSO",
    PARASITARIA = "PARASITARIA",
    INTOXICACION = "INTOXICACION",
    TRAUMATOLOGICA = "TRAUMATOLOGICA",
    OTRA = "OTRA",
    OJOS = "OJOS"
};

