export enum TipoEnfermedadEnum {
    RESPIRATORIA = "RESPIRATORIA",
    DIGESTIVA = "DIGESTIVA",
    SISTEMA_NERVIOSO = "SISTEMA_NERVIOSO",
    OJOS = "OJOS",
    PARASITARIA = "PARASITARIA",
    INTOXICACION = "INTOXICACION",
}